version: "3.9"
    
services:
  broker:
    image: eclipse-mosquitto 
    volumes:
      - type: bind
        source: ./mosquitto
        target: /mosquitto/config/
    ports:
      - "1885:1883"
  scratch:
    depends_on:
      - broker
    image: node
    volumes:
      - type: bind
        source: ./scratch-gui
        target: /app
    ports:
      - "8888:8601"
    working_dir: /app
    command: bash -c "npm install && npm start"
